version: "3.7"

services:
  db_brokerx:
    image: postgres
    container_name: db_brokerx
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=brokerx
    volumes:
      - pgdata:/data/postgres
    network_mode: host

  app:
    build: .
    container_name: brokerx
    depends_on:
      - db_brokerx
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    network_mode: host

volumes:
  pgdata:
